# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-ohai")
  raise "vagrant-ohai plugin is not installed! Install with 'vagrant plugin install vagrant-ohai'"
end

NODE_SCRIPT = <<EOF.freeze
  echo "Preparing node..."
  # ensure the time is up to date
  apt install ntp -y
  service start ntpd
  service enable ntpd
EOF

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure(2) do |config|

 config.vm.define 'testvps' do |n|
    #n.vm.box = 'ubuntu/xenial64'
    n.vm.box = "debian/jessie64"
    #n.vm.box_version = '2.2.9'
    n.vm.hostname = 'testdev'
    n.vm.network :private_network, ip: '192.168.10.43', nic_type: "virtio"
    n.vm.network "forwarded_port", guest: 80, host: 9000
    n.vm.provision :shell, inline: NODE_SCRIPT.dup
   set_hostname(n)
  end


end
